export enum ErrorCode {
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',

  UNAUTHORIZED = 'UNAUTHORIZED',
  UNAUTHORIZED__NO_USER = 'UNAUTHORIZED__NO_USER',
  UNAUTHORIZED__NO_TOKEN = 'UNAUTHORIZED__NO_TOKEN',
  UNAUTHORIZED__WRONG_PASSWORD = 'UNAUTHORIZED__WRONG_PASSWORD',
  UNAUTHORIZED__INVALID_TOKEN = 'UNAUTHORIZED__INVALID_TOKEN',

  CONFLICT = 'CONFLICT',
  CONFLICT__NICKNAME_ALREADY_EXISTS = 'CONFLICT__NICKNAME_ALREADY_EXISTS',
  CONFLICT__EMAIL_ALREADY_EXISTS = 'CONFLICT__EMAIL_ALREADY_EXISTS',

  NOT_FOUND = 'NOT_FOUND',
  NOT_FOUND__USER = 'NOT_FOUND__USER',
  NOT_FOUND__POST = 'NOT_FOUND__POST',
  NOT_FOUND__IMAGE = 'NOT_FOUND__IMAGE',
  NOT_FOUND__CHAT_ROOM = 'NOT_FOUND__CHAT_ROOM',

  BAD_REQUEST = 'BAD_REQUEST',
  BAD_REQUEST__STRING_TOO_LONG = 'BAD_REQUEST__STRING_TOO_LONG',
  BAD_REQUEST__STRING_TOO_SHORT = 'BAD_REQUEST__STRING_TOO_SHORT',
  BAD_REQUEST__INVALID_FILTER = 'BAD_REQUEST__INVALID_FILTER',
}
