export enum ErrorCode {
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  BAD_REQUEST = 'BAD_REQUEST',
  WRONG_PASSWORD = 'WRONG_PASSWORD',
  NICKNAME_ALREADY_EXISTS = 'NICKNAME_ALREADY_EXISTS',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  NOT_FOUND_USER = 'NOT_FOUND_USER',
  NOT_FOUND_POST = 'NOT_FOUND_POST',
  NOT_FOUND_IMAGE = 'NOT_FOUND_IMAGE',
  STRING_TOO_LONG = 'STRING_TOO_LONG',
  STRING_TOO_SHORT = 'STRING_TOO_SHORT',
}
